version: '3.7'

services:

  handyman-frontend:
    container_name: handyman-frontend
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start 